### ISSUE TITLE
Mod breaks bees

### ISSUE THREAD

**Issue by Mofabet** [GenMode/Minecraft#1]
Bees, regardless of the type, are magnetized to the ground and it is impossible to lift them even with a leash.

![2023-10-12_10 37 37](https://github.com/GenMode/Minecraft/assets/51799711/3037aec6-dd5f-4cd2-a20e-ec00e976398d)

**Comment by GenMode** [comment]
Oh thank you very much. This one is next in my update queue so I'll be on this very soon

In the meantime please see if disabling bees with the settings book restores their normal behavior. I'd appreciate that feedback very much
I think for your update the command is /function gen_baby:settings

**Comment by GenMode** [comment]
So I've looked into it and the issue seems to be specifically how the modloader is reading the datapack. I've hopefully got a fix for it that'll come out in the next few months

In the meantime feel free to install the datapack form of Better Babies to your world instead as it doesn't have the same bug as the mod form

**Comment by StrangeCorvus** [comment]
Yeah I've been having the same issue. Whenever the mod's active, all my bees just plum into the ground, and they keep spinning uncontrollably

**Comment by Sgordon4** [comment]
It looks like this issue occurs on both the Mod and the Datapack versions (1.20 v0.6). I've done some testing and will detail what I've found here:
- The bee issue appears to occur whenever _any_ baby models exist in the world, with correct bee behavior being restored when there are no custom baby models present in the world**.
- Not all models need to be disabled, just those for baby animals that currently exist**.
- The anomalous bee behavior persists even when the baby-containing chunks are unloaded. 

** In the attached video, the incorrect bee behavior persists even after the baby pig is forcibly removed, only reverting once the pig model is toggled. This was not initially the case in my tests, and unaliving the pig would return the bee to its correct behavior. This only appeared after using /kill @e.


https://github.com/GenMode/Minecraft/assets/37089894/ebe6f1c2-c8dc-4ae6-861a-70dbee577870

**Comment by GenMode** [comment]
Oh thank you so much I guess my test was wrong and it was a bug entirely on my part. Very sorry. I also wish I read this before I tried to fix it myself lol (didn't work). I heavily appreciate this info it's actually REALLY helpful and I'll forever be grateful

**Comment by GenMode** [comment]
LOL I PUT AN @e INSTEAD OF AN @s THAT'S HILARIOUS. Ight it'll be fixed in 0.6.2 thank you so much for the input
