### ISSUE TITLE
Requires Bedrock Edition adaptation.

### ISSUE THREAD

**Issue by Justintunsday** [GenMode/Minecraft#11]
Is it possible to make a specific Bedrock Edition adaptation for the Gen Asset Texture Pack?

**Comment by GenMode** [comment]
It's a resourcepack that contains all the assets for my datapacks. Since datapacks don't work on Bedrock Edition I'm sorry but that's probably not going to happen unless mojang makes them work together eventually

**Comment by Justintunsday** [comment]
I mean to make this ResourcePack compatible with Bedrock Edition through Geyser, not to recompile a new Data Pack.
