### ISSUE TITLE
(recipes plus) calcite block can be crafted from air

### ISSUE THREAD

**Issue by DrBruhman** [GenMode/Minecraft#15]
title

**Comment by GenMode** [comment]
what update are you on and can you provide a screenshot of the issue

**Comment by DrBruhman** [comment]
1.2.4+1.19.2
![изображение](https://github.com/user-attachments/assets/58fd7658-6f4c-4d1c-b76a-8d18f16ecb73)
(create) also if you click on crafting blueprint's slot this also show calcite as output, and it will craft calcite on click
![изображение](https://github.com/user-attachments/assets/38db7096-91af-4a18-8bb6-51e5167692d4)
1.5.0+1.19.2 Stonecutter Salvage, probably just EMI recipe view broke? there no different recipes for scraping stairs back to original block showing up but they are working.
![изображение](https://github.com/user-attachments/assets/acd99673-d0a5-44de-85ae-ecad2c1872f5)

**Comment by GenMode** [comment]
oh that's an interesting issue I wasn't aware of.

This is due to compatability with other mods but it seems the recipes aren't properly invalidating. Would you like me to send you and edited version of the datapack for you to use instead? and if so, what mods do you have installed so I can make sure those compatabilities stay

**Comment by GenMode** [comment]
also this is stonecutter salvage it's not recipes plus?

**Comment by DrBruhman** [comment]
could be this [mod](https://modrinth.com/mod/nerb) making calcite recipe valid?

ive checked, stonecutter recipes is fine.
mods list: [mods.txt](https://github.com/user-attachments/files/17567526/mods.txt)

**Comment by GenMode** [comment]
oh no don't worry it shouldn't be that mod. I was asking if this problem is with my "Recipes Plus"? since you mentioned Stonecutter Salvage but it wouldn't have a calcite recipe in it, Recipes Plus does

**Comment by GenMode** [comment]
ah ok I just checked your mod's list and yes Recipes Plus is installed. I won't be able to edit a mod within time but I'd be happy to send you a modified version of the datapack (works the exact same) to replace your Recipes Plus with that SHOULD fix the issue. You down for that?

**Comment by DrBruhman** [comment]
im making my modpack for my friends to share and managing so many recipes is tedious. im not longer using recipes plus and just here to report about this dupe.

**Comment by GenMode** [comment]
ok then thank you for your report I'll make sure to keep it in mind for the future
