### ISSUE TITLE
Gen's Villager Hats: When installed breaks hopper mechanics

### ISSUE THREAD

**Issue by Nitroito** [GenMode/Minecraft#16]
trading mechanics has nothing to do with storage mechanics but yet instaling the MOD it breaks hoppers.

hoppers stops pushing empty lava buckets from furnaces as well keeps filling the first hopper slot until is full, only then it starts pushing into chest from second slot.

**Mod Files:**
trade-villager-hats-0.1.16.jar
developer-resources-1.6.3.jar (Data API)
gen_assets.zip

**Minecraft 1.21.1**
Fabric Loader 0.16.7
Fabric API 0.106.0
Mod Menu 11.0.3

i tested the mod with only Mod Menu instaled.

Regards

**Comment by GenMode** [comment]
please run the command `/function gamerule:data_api/block_entities {set:"false"}` and tell me if that fixes it

**Comment by GenMode** [comment]
(forgot to put a closing post)

Issue closed as the related issue is now set to false by default
