### ISSUE TITLE
[1.20.1, Forge] Data API causes Pokecube NBT functions to use an absurd amount of server time

### ISSUE THREAD

**Issue by StardustPassingBy** [GenMode/Minecraft#4]
When used alongside Pokecube, it causes pretty much all of its NBT saving functions to hang up, causing massive tick lag. Here is a Spark log showing the issue:

https://spark.lucko.me/DIdwRsCWWy?hl=26463,21604,26468,26506,26499,26465,45045,45033,45043,45031,28065

Disabling the mod not only solves this issue but makes the game launch and load into the server much quicker.

**Comment by GenMode** [comment]
I'm not sure what could be doing that since Data API is a datapack. It shouldn't be interfering with any mod in particular as all the functions are vanilla. Although I'm in the works with a more streamlined update of Data API so hopefully that fixes it in the future
