### ISSUE TITLE
Mods not working on 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [GenMode/Minecraft#6]
Better Babies, Villager Hats and Data API.
https://pastebin.com/raw/CvfEJWUq

**Comment by StrangeCorvus** [comment]
Yeah i'm having the same issue. It's my third time giving this mod a chance and it's not working, again.
This mod straight up never worked for me, I try testing it every time with a fresh install when the game gets updated but nothing.

The first time I ever tried it, they were invisible, the second time they were floating item frames, and now the mod is straight up doing nothing. 

I love the concept, I just wish it worked

**Comment by GenMode** [comment]
These projects now have versions compatible with the minecraft 1.20.6 update
