### ISSUE TITLE
[Suggestion] Cheaper Chain Recipe

### ISSUE THREAD

**Issue by DJChaos42** [GenMode/Minecraft#7]
The addition of recipes for chainmail armor is nice, but the way they are currently implemented is a little impractical because of the way chains are crafted. One chain costs one iron ingot and two iron nuggets to craft, meaning that it is slightly more expensive to craft chainmail armor than iron armor. Granted it's not by much, with a full set of chainmail armor costing just over five more ingots to craft than iron armor, but it's enough that it might dissuade players from crafting it in the early game when it would be most useful.

I would suggest making the chain recipe either cost less than one iron ingot per chain, or yield more than one chain. That would provide a stronger incentive for players to craft chain armor.

**Comment by GenMode** [comment]
thank you for your feedback I'll take it into consideration

**Comment by GenMode** [comment]
This feature has now been implemented in the latest version 1.1.0
