### ISSUE TITLE
Mod does nothing no matter what I do.

### ISSUE THREAD

**Issue by StrangeCorvus** [GenMode/Minecraft#8]
I'm playing on 1.21 
It's the fourth time I try downloading this, the mod changes absolutely nothing. The previous times I tried it, it was straight-up broken.

I have all the dependencies, mods that make custom models work properly, but nothing works.
The mod site says that the mod got recently updated, but it still won't work for me

**Comment by GenMode** [comment]
I'm very sorry it turns out Minecraft 1.21 broke the code for these things. I'm currently working on a fix currently and I'll update you when it comes out

**Comment by MrPlayerYork** [comment]
May I suggest that you update the modrinth page to reflect this?

**Comment by graemeg** [comment]
Yeah, I've just been trying for the last hour trying to get it to work 1.21 took. Looked at the wiki about using a Spyglass etc. Nothing happens. I think modrinth should reflect that it's currently not working in 1.21.

**Comment by GanerCodes** [comment]
yeah same i was wondering why it wasnt working

**Comment by GenMode** [comment]
I forgot to notify here sorry but yes as of a week ago Better Babies and Data API are both patched to now work in Minecraft 1.21
