### ISSUE TITLE
Campfires (soul and regular) deactivate hoppers placed beneath the campfire.

### ISSUE THREAD

**Issue by babarsc** [GenMode/Minecraft#9]
After installing Data_API, Better Babies and the Gen resource pack, hoppers no longer pick up items through campfires.  This broke an afk creeper farm.

edit: Hoppers are actually deactivated completely if placed under campfires (soul and regular).  Items cannot pass through a hopper if a campfire is located above it.  No other direction seems to be affected. (i.e. campfire to side or below hopper, only if campfire is on top). 

Tested both Fabric and Datapack on 1.20.6, single player and server.

**Comment by babarsc** [comment]
Just ran another test.  campfires (soul and regular) deactivate hoppers below them completely.  Items can't even pass through a hopper below a campfire.

**Comment by GenMode** [comment]
Thank you for this note, I'll keep this in mind for the future

**Comment by GenMode** [comment]
As of now this bug has been fixed in the most recent update
